 version: "3.9"
 services:
   db:
     image: postgres:15
     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: linkwise
     ports:
       - "5432:5432"
     volumes:
       - pgdata:/var/lib/postgresql/data
     healthcheck:
       test: ["CMD-SHELL", "pg_isready -U postgres"]
       interval: 5s
       timeout: 5s
       retries: 10

   redis:
     image: redis:7-alpine
     ports:
       - "6379:6379"

   api:
     build:
       context: ./backend
     environment:
       DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/linkwise
       REDIS_URL: redis://redis:6379/0
       PORT: 8000
     depends_on:
       db:
         condition: service_healthy
     ports:
       - "8000:8000"

   web:
     build:
       context: ./frontend
     ports:
       - "3000:3000"
     environment:
       NEXT_PUBLIC_API_BASE_URL: http://localhost:8000
     depends_on:
       - api

 volumes:
   pgdata:

